### ISSUE TITLE
How to use in cakephp 3

### ISSUE THREAD

**Issue by LDSign** [burzum/cakephp-database-log#2]
Hi

Ive installed this plugin via composer in the vendor dir. Could you provide a short example how to load and use it?

Thanks,
Frank

**Comment by burzum** [comment]
Hi Frank, 

please take at least one minute to read the readme.md, the landing page of the repository.

https://github.com/burzum/cakephp-database-log#documentation

> Please check the official documentation on how to use logging adapters.

It has a link to the official documentation that explains all about logging in Cake3, including how to use a log engine.

**Comment by LDSign** [comment]
Hi

Sure, I have read this ;) But I had no success in including your LogEngine from the vendor directory :(

Frank

**Comment by burzum** [comment]
The autoloader will take care of that.

See http://book.cakephp.org/3.0/en/core-libraries/logging.html#creating-log-adapters

Just change the name of the plugin prefix to mine: `Burzum/DatabaseLog.DatabaseLog`

You really just have to read through that page. This plugin implements exactly what is described on this page. That was the whole intention of this plugin.

**Comment by LDSign** [comment]
Hi Florian

Unfortunatley I can't get it work :( Ive added the log config to app.php like this (see test):

``` php
`    /**
     * Configures logging options
     */
    'Log' => [
        'debug' => [
            'className' => 'Cake\Log\Engine\FileLog',
            'path' => LOGS,
            'file' => 'debug',
            'levels' => ['notice', 'info', 'debug'],
        ],
        'error' => [
            'className' => 'Cake\Log\Engine\FileLog',
            'path' => LOGS,
            'file' => 'error',
            'levels' => ['warning', 'error', 'critical', 'alert', 'emergency'],
        ],
        'test' => [
            'className' => 'Burzum/DatabaseLog.DatabaseLog',
            'model' => 'LogEntry',
        ]

    ],`
```

But I always get:

`Could not load class DatabaseLog`

Same is for custom created ones in src/Log/Engine. Obviously I am missing something, but what?

Thanks for your help again,
Frank

**Comment by burzum** [comment]
The official documentation is wrong...

``` php
'className' => 'Burzum/DatabaseLog.DatabaseLog',
```

Try to remove the `Log` at the end of the name.

``` php
'className' => 'Burzum/DatabaseLog.Database',
```

And don't forget to run migrations or it will very likely complain about the missing table. I'll add some docs to the plugin.

The reason for this is you can either use the absolute class name there `Burzum\DatabaseLog\Log\Engine\DatabaseLog` or a short name and plugin dot notation that Cake will try to lookup and turn into a class name for convenience.

**Comment by burzum** [comment]
See https://github.com/burzum/cakephp-database-log/blob/master/docs/Installation.md

I've tagged version 1.0.1, run composer update, but there are no real changes, just the documentation update.

**Comment by LDSign** [comment]
Hi Florian

Ok, thanks - everything works fine now :) Glad to hear that this was documentation related _g_

Frank

**Comment by burzum** [comment]
The documentation has already been fixed in the repository but looks like the documentation site was not yet regenerated. See https://github.com/cakephp/docs/blob/master/en/core-libraries/logging.rst#creating-and-configuring-log-streams This happened very likely because this was changed more or less recently. Before you were required to add the Log suffix.
